# Generated by Django 3.1.7 on 2021-03-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_cart_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='discount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3),
        ),
    ]
