# Generated by Django 3.1.7 on 2021-03-21 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20210320_2224'),
        ('orders', '0002_auto_20210320_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_profiles',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.billingprofile'),
        ),
    ]
