# Generated by Django 3.1.7 on 2021-03-21 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='billing_profiles',
            new_name='billing_profile',
        ),
    ]
