# Generated by Django 3.1.7 on 2021-03-21 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_address'),
        ('orders', '0005_auto_20210321_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_address', to='billing.address'),
        ),
        migrations.AddField(
            model_name='order',
            name='shpping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shpping_address', to='billing.address'),
        ),
    ]
