# Generated by Django 3.1.7 on 2021-03-21 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20210321_0313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shpping_address',
            new_name='shipping_address',
        ),
    ]
